using System;
using System.Collections;
using System.Collections.Generic;
using Cinemachine;
using UnityEngine;
using UnityEngine.Serialization;

public class CannonAttack : MonoBehaviour
{
    private IntObjectInputManager 覺ntObjectInputManager;
    
    [SerializeField]
    private Transform bulletSpawnPoint;

    [SerializeField]
    private CannonBall cannonBall;

     [SerializeField] private Transform cannonHead;

    Cinemachine.CinemachineImpulseSource source;

     
     public CinemachineVirtualCamera cam;
    private void Awake()
    {
        覺ntObjectInputManager = GetComponent<IntObjectInputManager>();
        source = GetComponent<CinemachineImpulseSource>();
        

    }

    private void OnEnable()
    {
        覺ntObjectInputManager.R1Action += Attack;
    }

    private void OnDisable()
    {
        覺ntObjectInputManager.R1Action -= Attack;
    }

    void Attack()
    {
        cannonBall.addCannonBall(bulletSpawnPoint,cannonHead.transform.rotation);
       // SoundEffectManager.Instance.SoundEffect(SoundEffectManager.Instance.cannonShootClip,true);
        //source.GenerateImpulse(transform.up);
        source.GenerateImpulse(cam.transform.up);
    }
    
 
}
